WebApp/Controllers/ClearController.cs
using Microsoft.AspNetCore.Mvc;
using RedisRepository.Interfaces;
using System;
using WebApp.Services;

namespace WebApp.Controllers
{
    public class ClearController : Controller
    {
        private readonly IRedisRepositoryBase _redisRepository;

        public ClearController(IRedisRepositoryBase redisRepository)
        {
            _redisRepository = redisRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Clear()
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _redisRepository.Clear();

                    new SetTempDataMessage()
                        .Display(TempData, "OK", "Data cleared.");
                }
            }
            catch (Exception ex)
            {
                new SetTempDataMessage()
                    .Display(TempData, "Error", ex.Message, SetTempDataMessage.CssClassNameEnum.alert_danger);
            }

            return View("Index");
        }
    }
}

WebApp/Controllers/DeleteController.cs
using Microsoft.AspNetCore.Mvc;
using RedisRepository.Interfaces;
using System;
using WebApp.Models;
using WebApp.Services;

namespace WebApp.Controllers
{
    public class DeleteController : Controller
    {
        private readonly IRedisRepositoryBase _redisRepository;

        public DeleteController(IRedisRepositoryBase redisRepository)
        {
            _redisRepository = redisRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(DeleteViewModel viewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (_redisRepository.Exists(viewModel.KeyToDelete))
                    {
                        _redisRepository.Delete(viewModel.KeyToDelete);

                        new SetTempDataMessage()
                            .Display(TempData, "OK", $"The key {viewModel.KeyToDelete} has been removed.");
                    }
                    else
                    {
                        new SetTempDataMessage()
                            .Display(TempData, "Warning", $"Key {viewModel.KeyToDelete} was not found.", SetTempDataMessage.CssClassNameEnum.alert_warning);
                    }
                }
            }
            catch (Exception ex)
            {
                new SetTempDataMessage()
                    .Display(TempData, "Error", ex.Message, SetTempDataMessage.CssClassNameEnum.alert_danger);
            }

            return View(viewModel);
        }
    }
}

WebApp/Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using RedisRepository;
using RedisRepository.enums;
using RedisRepository.Interfaces;
using WebApp.Models;
using WebApp.Services;

namespace WebApp.Controllers
{
    public class InfoController : Controller
    {
        private readonly IRedisRepositoryBase _redisRepository;
        private readonly DatabaseOptions _databaseOptions;

        public InfoController(IRedisRepositoryBase redisRepository, IOptions<DatabaseOptions> options)
        {
            _redisRepository = redisRepository;
            _databaseOptions = options.Value;
        }

        public IActionResult Index()
        {
            var viewModel = new InfoViewModel()
            {
                Info = _redisRepository.Info(InfoEnum.Info.All),
                Filter = SetDropDownList(),
                Connection = _databaseOptions.ConnectionString
            };
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Index(InfoViewModel viewModel)
        {
            Enum.TryParse(viewModel.SelectedFilter, out InfoEnum.Info infoParameter);

            viewModel.Info = _redisRepository.Info(infoParameter);
            viewModel.Filter = SetDropDownList();
            viewModel.Connection = _databaseOptions.ConnectionString;
            return View(viewModel);          
        }

        private List<SelectListItem> SetDropDownList()
        {
            var returnList = new List<SelectListItem>();
            var infoEnumList = Enum.GetValues(typeof(InfoEnum.Info));

            foreach (var infoEnum in infoEnumList)
            {
                returnList.Add(new SelectListItem() {
                    Value = infoEnum.ToString(),
                    Text = infoEnum.ToString()
                });
            }

            return returnList;
        }
    }
}

WebApp/Controllers/SelectListController.cs
using Microsoft.AspNetCore.Mvc;
using RedisRepository.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class SelectListController : Controller
    {
        private readonly IRedisRepositoryBase _redisRepository;
        private readonly IRedisRepositoryString _redisRepositoryString;
        private readonly IRedisRepositorySortedSet _redisRepositorySortedSet;

        public SelectListController(IRedisRepositoryBase redisRepository, IRedisRepositoryString redisRepositoryString, IRedisRepositorySortedSet redisRepositorySortedSet)
        {
            _redisRepository = redisRepository;
            _redisRepositoryString = redisRepositoryString;
            _redisRepositorySortedSet = redisRepositorySortedSet;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(SelectListViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var keyList = _redisRepository
                    .SelectListScan(viewModel.SearchOnKey, 1000)
                    .ToList();

                var newList = new List<string>();
                foreach (var key in keyList)
                {
                    newList.Add("<div class='keyResult' data-toggle='modal' data-target='#myModal' data-key='"+key+"'>"+key+"</div>");
                }

                viewModel.Result = string.Join(Environment.NewLine, newList);
                viewModel.ResultCount = keyList.Count();
            }

            return View(viewModel);
        }

        // TODO ~ move these private methods into a service

        public ActionResult ZoomOnKey(string key)
        {
            var keyType = _redisRepository.GetType(key).ToString();

            var viewModel = new ZoomViewModels()
            {
                Key = key,
                Type = keyType,
                ValueData = ReadValue(key, keyType)
            };
            return PartialView("_ZoomOnKey", viewModel);
        }

        private ValueDataViewModel ReadValue(string key, string keyType)
        {
            if (keyType == "String")
            { 
                return new StringTypeViewModel()
                {
                    Value = _redisRepositoryString.Select(key)
                };
            }

            if (keyType == "SortedSet")
            {
                var valueData = new SortedSetWithScoreViewModel()
                {
                    Data = new List<List<string>>()
                };

                var counter = 0;
                foreach (var member in _redisRepositorySortedSet.SelectListRecordWithScore(key))
                {
                    valueData.Data.Add(new List<string>(){
                        counter.ToString(),
                        member.Item1.ToString(),
                        member.Item2
                        });


                    counter++;
                }
                return valueData;
            }

            return new ValueDataViewModel();
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Redis Administrator</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="~/jquery-ui-1.12.1.custom/jquery-ui.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />
    </environment>

    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Redis Administrator</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link text-dark" asp-controller="Info" asp-action="Index">Info</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link text-dark" asp-controller="SelectList" asp-action="Index">Search</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" id="dropdown01" asp-area="" asp-controller="Seed" data-toggle="dropdown">Seed</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown01">
                                <a class="dropdown-item" asp-controller="Seed" asp-action="Index">Seed Help</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-controller="Seed" asp-action="StringType">String Type</a>
                                <a class="dropdown-item" asp-controller="Seed" asp-action="SortedSetType">Sorted Set Type</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" id="dropdown02" asp-area="" asp-controller="Seed" data-toggle="dropdown">Admin Tools</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown02">
                                <a class="dropdown-item" asp-controller="Clear" asp-action="Index">Clear</a>
                                <a class="dropdown-item" asp-controller="Delete" asp-action="Index">Delete By Key</a>
                                <a class="dropdown-item" asp-controller="DeleteByScore" asp-action="Index">Delete By Score</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" id="dropdown03" asp-area="" asp-controller="Home" data-toggle="dropdown">Help</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown03">
                                <a class="dropdown-item" asp-controller="Home" asp-action="Help">General</a>
                                <a class="dropdown-item" asp-controller="Score" asp-action="Index">Score</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @{
        var assembly = System.Reflection.Assembly.GetExecutingAssembly();
        var infoVersionAttr = assembly.GetCustomAttributes(typeof(System.Reflection.AssemblyInformationalVersionAttribute), false)
            .Cast<System.Reflection.AssemblyInformationalVersionAttribute>()
            .FirstOrDefault();
        var version = infoVersionAttr?.InformationalVersion?.Split('+')[0] ?? assembly.GetName().Version.ToString();
    }

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.ToString("yyyy") - <a asp-area="" asp-controller="Home" asp-action="Privacy">Redis Administrator</a>
            is powered by <a href="https://getbootstrap.com/docs/4.0/getting-started/introduction/" target="_blank">Bootstrap</a>
            and <a href="https://github.com/StackExchange/StackExchange.Redis/" target="_blank">StackExchange.Redis</a> 
            v @version
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>

    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>